# Generated by Django 5.0.1 on 2024-02-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='clients',
            field=models.ManyToManyField(to='modelapp.client'),
        ),
    ]
