# Generated by Django 5.0.1 on 2024-02-16 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_alter_person_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypothesis_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lawyer',
            name='disposition',
            field=models.ManyToManyField(to='modelapp.disposition'),
        ),
        migrations.AddField(
            model_name='client',
            name='hypothesis',
            field=models.ManyToManyField(to='modelapp.hypothesis'),
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(default='Jhon Doe', on_delete=django.db.models.deletion.SET_DEFAULT, to='modelapp.client')),
                ('lawyer', models.ForeignKey(default='Rollo Tomassi', on_delete=django.db.models.deletion.SET_DEFAULT, to='modelapp.lawyer')),
                ('sanction', models.ForeignKey(default='Do Nothing', on_delete=django.db.models.deletion.SET_DEFAULT, to='modelapp.sanction')),
            ],
        ),
    ]
